'use client';
import { useCallback, useEffect, useState } from 'react';
import { DraftSection, GuestRoom } from '@concord/shared';
import { ConcordWordmark } from '@/components/ConcordBrand';
import { RequestError, RequestLoading, requestDate, errorMessage } from '@/components/RequestUI';
import DocumentComparison from '@/components/DocumentComparison';

class RoomError extends Error { constructor(message: string, readonly status: number) { super(message); } }
export default function GuestReviewRoom({ params }: { params: { id: string } }) {
  const base = `/api/negotiation/guest/${encodeURIComponent(params.id)}`;
  const [room,setRoom] = useState<GuestRoom>(), [ready,setReady] = useState(false), [email,setEmail] = useState(''), [challenge,setChallenge] = useState(''), [code,setCode] = useState('');
  const [error,setError] = useState(''), [notice,setNotice] = useState(''), [busy,setBusy] = useState(false), [cooldown,setCooldown] = useState(0), [tab,setTab] = useState('document');
  const [editing,setEditing] = useState(false), [sections,setSections] = useState<DraftSection[]>([]), [comment,setComment] = useState(''), [responseId,setResponseId] = useState(() => crypto.randomUUID()), [confirmed,setConfirmed] = useState(false);
  const [needsAuth,setNeedsAuth] = useState(false), [incoming,setIncoming] = useState<GuestRoom>();
  const dirty = !!room && JSON.stringify(sections) !== JSON.stringify(room.sections);
  const send = useCallback(async <T,>(path = '', body?: unknown): Promise<T> => {
    const form = body instanceof FormData;
    const res = await fetch(base + path,{ credentials: 'same-origin', cache: 'no-store', ...(body !== undefined ? { method: 'POST', headers: form ? undefined : { 'Content-Type': 'application/json' }, body: form ? body : JSON.stringify(body) } : {}) });
    const json = await res.json().catch(() => ({}));
    if (!res.ok) throw new RoomError(Array.isArray(json.message) ? json.message.join(' · ') : json.message || 'The review room could not complete this action.',res.status);
    return json;
  },[base]);
  const load = useCallback(async () => { try { const next = await send<GuestRoom>(); setRoom(next); setSections(next.sections); } catch(e) { if (!(e instanceof RoomError && e.status === 401)) setError(errorMessage(e)); } finally { setReady(true); } },[send]);
  useEffect(() => { void load(); },[load]);
  useEffect(() => { if (!cooldown) return; const timer = setTimeout(() => setCooldown(c => c-1),1000); return () => clearTimeout(timer); },[cooldown]);
  useEffect(() => { if (!dirty) return; const warn = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ''; }; window.addEventListener('beforeunload',warn); return () => window.removeEventListener('beforeunload',warn); },[dirty]);
  async function run(fn: () => Promise<void>) { if (busy) return; setBusy(true); setError(''); setNotice(''); try { await fn(); } catch(e) { setError(errorMessage(e)); if (e instanceof RoomError && e.status === 401) { setNeedsAuth(true); setChallenge(''); setCode(''); } } finally { setBusy(false); } }
  return <main className="guest-room"><header className="guest-brand"><ConcordWordmark variant="display" /><span>Secure agreement review</span></header>
    {!ready ? <RequestLoading /> : !room || needsAuth ? <section className="card guest-login"><span className="section-kicker">Invited participants</span><h1>{needsAuth ? 'Resume your review.' : 'A private place to agree.'}</h1>{needsAuth && <p className="editor-notice">Verify your email again. Your unsaved suggestions remain in this tab.</p>}<p>Enter the email address Legal invited. Your verification code gives you access to this agreement.</p><form className="req-form" onSubmit={e => { e.preventDefault(); void run(async () => { if (challenge) { await send('/verify',{ email, challengeId: challenge, code }); setCode(''); const next = await send<GuestRoom>(); if (room && dirty) { if (next.documentId === room.documentId) setRoom(next); else setIncoming(next); } else { setRoom(next); setSections(next.sections); } setNeedsAuth(false); } else { const result = await send<{ challengeId: string; message: string }>('/challenge',{ email }); setChallenge(result.challengeId); setNotice(result.message); setCooldown(60); } }); }}><label className="req-field">Invited email<input required type="email" autoComplete="email" value={email} readOnly={!!challenge} onChange={e => setEmail(e.target.value)} /></label>{challenge && <label className="req-field">Verification code<input required inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} value={code} onChange={e => setCode(e.target.value.replace(/\D/g,''))} /></label>}{error && <RequestError message={error} />}{notice && <p className="req-note" role="status">{notice}</p>}<button className="btn btn-gold" disabled={busy}>{busy ? 'Please wait…' : challenge ? 'Enter agreement review' : 'Send verification code'}</button>{challenge && <button className="btn" type="button" disabled={busy || cooldown > 0} onClick={() => { setChallenge(''); setCode(''); setNotice(''); }}>{cooldown ? `Request another code in ${cooldown}s` : 'Change email or request a new code'}</button>}</form><p className="req-help">Codes expire after 10 minutes. An expired or revoked invitation needs a new invitation from Legal.</p></section> : <>
    <header className="guest-agreement-header"><div><span className="section-kicker">Round {room.round} · Shared by {room.sharedBy}</span><h1>{room.title}</h1><p>{room.participant} · {room.organisation}</p></div><div><span className="badge neutral">{room.accepted ? 'Draft accepted' : room.response ? 'With Legal' : 'Your review'}</span><p>{room.dueAt ? `Response due ${requestDate(room.dueAt)}` : `Access until ${requestDate(room.expiresAt)}`}</p></div></header>
    <nav className="agreement-tabs guest-tabs" aria-label="Agreement review sections">{[['document','Document'],['comments','Comments'],['changes','Changes'],['activity','Activity']].map(([key,label]) => <button key={key} aria-current={tab === key ? 'page' : undefined} onClick={() => setTab(key)}>{label}</button>)}</nav>{error && <RequestError message={error} />}{notice && <p className="editor-notice" role="status">{notice}</p>}
    {incoming && <section className="card card-pad"><h2>Legal shared a new version</h2><p>Your unsaved proposal is still available below. Compare it with Legal’s latest version before choosing what to keep.</p><DocumentComparison before={incoming.sections} after={sections} /><div className="req-actions"><button className="btn" onClick={() => { setRoom(incoming); setSections(incoming.sections); setIncoming(undefined); setResponseId(crypto.randomUUID()); setConfirmed(false); setEditing(false); }}>Use Legal’s latest version</button><button className="btn btn-gold" disabled={!incoming.canRedline} onClick={() => { setRoom(incoming); setIncoming(undefined); setResponseId(crypto.randomUUID()); setConfirmed(false); setEditing(true); setNotice('Your proposal is now compared against Legal’s latest version. Review every difference before submitting.'); }}>Keep my proposal for review</button></div></section>}

    {tab === 'document' && <section className="card guest-document"><div className="editor-toolbar">{room.canDownload && <a className="btn" href={`${base}/file`}>Download Word</a>}{room.canRedline && <button className="btn" aria-pressed={editing} onClick={() => setEditing(!editing)}>{editing ? 'Preview document' : 'Suggest Changes'}</button>}{room.canUpload && <label className="btn guest-upload">Upload Word redline<input type="file" accept=".docx" disabled={busy || dirty} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void run(async () => { const form = new FormData(); form.append('file',file); form.append('id',responseId); form.append('documentId',room.documentId); await send('/upload',form); await load(); setNotice('Your Word response is saved. Legal will review it.'); setResponseId(crypto.randomUUID()); }); e.target.value = ''; }} /></label>}</div>
      <div className="guest-document-body">{sections.map((s,i) => <section className="shared-clause" key={s.id ?? i}>{s.kind !== 'paragraph' && <h3>{s.heading}</h3>}{editing && room.canRedline ? <label className="req-field"><span className="sr-only">Proposed language for {s.heading}</span><textarea rows={Math.min(12,Math.max(4,Math.ceil(s.body.length/100)))} maxLength={50000} value={s.body} onChange={e => { setSections(rows => rows.map((r,j) => i === j ? { ...r, body: e.target.value } : r)); setConfirmed(false); }} /></label> : <p>{s.body}</p>}</section>)}</div>
      {dirty && <div className="editor-footer"><p>Your suggestions stay here until you submit them.</p><button className="btn btn-gold" onClick={() => setTab('changes')}>Review my changes →</button></div>}
      {room.canAccept && !incoming && !dirty && !room.accepted && <div className="editor-footer"><label className="req-check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />I have reviewed this shared draft.</label><button className="btn btn-gold" disabled={busy || !!incoming || !confirmed} onClick={() => void run(async () => { await send('/accept',{ documentId: room.documentId }); await load(); setNotice('Your acceptance of this draft is recorded. Signature will be arranged separately.'); })}>Accept Current Draft</button></div>}
    </section>}
    {tab === 'changes' && <section className="card card-pad"><h2>{room.response ? 'Response submitted' : 'Review your proposed changes'}</h2>{room.response ? <><p>Your response was saved {requestDate(room.response.createdAt)}. Legal will review it before sharing a new version.</p><p>{room.response.changes.length} clause changes recorded.</p></> : <><DocumentComparison before={room.sections} after={sections} />{dirty && room.canRedline && <><label className="req-check"><input type="checkbox" checked={confirmed} onChange={e => setConfirmed(e.target.checked)} />These are the changes I want to submit to Legal.</label><div className="req-actions"><button className="btn" onClick={() => { setEditing(true); setTab('document'); }}>Continue editing</button><button className="btn btn-gold" disabled={busy || !!incoming || !confirmed} onClick={() => void run(async () => { await send('/response',{ id: responseId, documentId: room.documentId, sections }); await load(); setEditing(false); setConfirmed(false); setResponseId(crypto.randomUUID()); setNotice('Changes submitted. The earlier shared version is preserved.'); })}>Submit Changes</button></div></>}</>}</section>}
    {room.executedAvailable && <section className="card card-pad"><span className="section-kicker">Agreement completed</span><h2>Your executed agreement</h2><p>Legal has shared the authoritative signed copy with you.</p><a className="btn btn-gold" href={`${base}/executed`}>Download executed PDF</a></section>}
    {tab === 'comments' && <section className="card card-pad"><h2>Shared discussion</h2><p className="req-help">These comments are visible to Legal and the participants invited to this shared version.</p><ul className="editor-comments">{room.comments.map(c => <li key={c.id}><b>{c.authorName}</b><small>{requestDate(c.createdAt)}{c.resolvedAt ? ' · Resolved' : ''}</small><p>{c.body}</p></li>)}</ul>{room.canComment && <form className="req-form" onSubmit={e => { e.preventDefault(); void run(async () => { await send('/comments',{ id: crypto.randomUUID(), documentId: room.documentId, body: comment }); setComment(''); const next = await send<GuestRoom>(); if (next.documentId !== room.documentId && dirty) { setIncoming(next); } else { setRoom(next); if (next.documentId !== room.documentId) setSections(next.sections); } }); }}><label className="req-field">Comment or reply<textarea required rows={3} maxLength={6000} value={comment} onChange={e => setComment(e.target.value)} /></label><button className="btn btn-gold" disabled={busy || !comment.trim()}>Post comment</button></form>}</section>}
    {tab === 'activity' && <section className="card card-pad"><h2>Shared activity</h2><ol className="conversation-list"><li><small>{requestDate(room.sharedAt)}</small><p>Legal shared round {room.round}.</p></li>{room.response && <li><small>{requestDate(room.response.createdAt)}</small><p>Your response was submitted to Legal.</p></li>}{room.comments.map(c => <li key={c.id}><small>{requestDate(c.createdAt)}</small><p>{c.authorName} added a shared comment.</p></li>)}</ol></section>}
    <button className="btn guest-signout" disabled={busy} onClick={() => void run(async () => { const next = await send<GuestRoom>(); if (dirty && next.documentId !== room.documentId) setIncoming(next); else { setRoom(next); if (!dirty) setSections(next.sections); setNotice('You are viewing the latest version shared with you.'); } })}>Check for Legal’s response</button>
    <button className="btn guest-signout" disabled={busy} onClick={() => { if (dirty && !window.confirm('Sign out without submitting your changes?')) return; void run(async () => { await send('/logout',{}); setRoom(undefined); setSections([]); setIncoming(undefined); setNeedsAuth(false); setChallenge(''); setCode(''); }); }}>Sign out of this review room</button>
    </>}
    <footer className="guest-footer">Built by Lakmē Legal for Lakmē Lever.</footer>
  </main>;
}
