'use client';
import { useCallback, useEffect, useState } from 'react';
import { ROLES, ROLE_LABELS } from '@concord/shared';
import type { Role } from '@concord/shared';
import { addTeamUser, getAccessStatus, getMe, getTeamUsers, setTeamRole } from '@/app/lib/api';
import type { TeamUser } from '@/app/lib/api';
import { errorMessage, RequestError, RequestHeader, RequestLoading } from '@/components/RequestUI';
function RoleSelect({ value, change, disabled, label = 'Access role' }: { value: Role; change: (role: Role) => void; disabled?: boolean; label?: string }) {
  return <label className="req-field">{label}<select value={value} disabled={disabled} onChange={e => change(e.target.value as Role)}>{ROLES.map(role => <option key={role} value={role}>{ROLE_LABELS[role]}</option>)}</select></label>;
}
export default function TeamPage() {
  const [users, setUsers] = useState<TeamUser[]>(); const [roles, setRoles] = useState<Record<string, Role>>({}); const [me, setMe] = useState('');
  const [status, setStatus] = useState<{ microsoftSignInConfigured: boolean; outlookConfigured: boolean }>();
  const [portal, setPortal] = useState(''); const [error, setError] = useState(''); const [saved, setSaved] = useState(''); const [busy, setBusy] = useState(false);
  const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [role, setRole] = useState<Role>('requester');
  const load = useCallback(async () => { try { const [team, access, current] = await Promise.all([getTeamUsers(), getAccessStatus(), getMe()]); setUsers(team); setStatus(access); setMe(current.id); setRoles(Object.fromEntries(team.map(u => [u.id, u.canonicalRole]))); } catch(e) { setError(errorMessage(e)); } }, []);
  useEffect(() => { setPortal(`${window.location.origin}/requests`); void load(); }, [load]);
  async function perform(action: () => Promise<unknown>, success: string) { if (busy) return; setBusy(true); setError(''); setSaved(''); try { await action(); await load(); setSaved(success); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  async function add(e: React.FormEvent) { e.preventDefault(); await perform(async () => { await addTeamUser({ name, email, role }); setName(''); setEmail(''); }, 'Account added. This person can use their corporate Microsoft identity once sign-in is connected.'); }
  return <div className="req-page"><RequestHeader kicker="Administration" title="Team & access" description="Give each colleague the right workspace. Department clients raise requests; your legal team receives and manages them." />{error && <RequestError message={error} retry={() => { setError(''); void load(); }} />}{saved && <p className="req-success" role="status">{saved}</p>}{!users && !error ? <RequestLoading /> : users && <>
    <section className="req-panel"><h3>Share the department portal</h3><a className="req-share-link" href={portal}>{portal}</a><p>Add colleagues with the <b>Department client</b> role, then share this link. They sign in with their own authorised Microsoft account and see only the requests they raise.</p><div className="req-inline"><span className="req-status">Microsoft sign-in · {status?.microsoftSignInConfigured ? 'Configured' : 'Setup required'}</span><span className="req-status">Outlook email · {status?.outlookConfigured ? 'Configured' : 'Setup required'}</span></div>{(!status?.microsoftSignInConfigured || !status?.outlookConfigured) && <p className="req-help">Your IT administrator needs to connect the organisation’s Microsoft tenant. New accounts use Microsoft sign-in; this screen does not create passwords or send invitations.</p>}</section>
    <section className="req-panel"><h3>Add a colleague</h3><p className="req-help">Use their corporate Microsoft email. Counsel, Legal Lead and Administrator accounts appear in the legal contact dropdown.</p><form className="req-form" onSubmit={add}><div className="req-fields"><label className="req-field">Full name *<input value={name} onChange={e => setName(e.target.value)} required maxLength={160} disabled={busy} autoComplete="off" /></label><label className="req-field">Corporate email *<input type="email" value={email} onChange={e => setEmail(e.target.value)} required maxLength={254} disabled={busy} autoComplete="off" /></label><RoleSelect value={role} change={setRole} disabled={busy} /><div className="req-field"><span>Access</span><small>{role === 'requester' ? 'Own agreement requests and personal inbox only.' : 'Legal workspace access according to the selected role.'}</small></div></div><div className="req-actions"><span className="req-help">Every account grant is recorded in the audit trail.</span><button className="btn btn-gold" disabled={busy}>{busy ? 'Saving…' : 'Add colleague'}</button></div></form></section>
    <section className="req-panel"><h3>{users.length} team {users.length === 1 ? 'member' : 'members'}</h3>{users.map(user => <div className="req-team-row" key={user.id}><div><b>{user.name}{user.id === me ? ' (you)' : ''}</b><small>{user.email}</small><small>{user.roleSource === 'manual' ? 'Access assigned in Concord' : 'Access managed through Microsoft'}</small></div><RoleSelect value={roles[user.id] ?? user.canonicalRole} change={next => setRoles(r => ({ ...r, [user.id]: next }))} disabled={busy || user.id === me} label={`Role for ${user.name}`} /><button className="btn" disabled={busy || user.id === me || roles[user.id] === user.canonicalRole} onClick={() => void perform(() => setTeamRole(user.email, roles[user.id]), `Access updated for ${user.name}.`)}>Save<span className="sr-only"> access for {user.name}</span></button></div>)}</section>
  </>}</div>;
}
