import React from 'react';
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {useLocalSearchParams,useRouter} from 'expo-router';
import {ForgeBrand} from '@/components/ForgeBrand';
import {GlassCard} from '@/components/GlassCard';
import {useForge,exerciseMap} from '@/store/ForgeProvider';
import {shortDate} from '@/utils/format';
export default function ExerciseHistory(){
 const router=useRouter(),{exerciseId}=useLocalSearchParams<{exerciseId:string}>(),{state,theme}=useForge(),ex:any=exerciseMap[exerciseId||''];
 const rows=(state.sessions||[]).flatMap(s=>(s.exercises||[]).filter(x=>x.exerciseId===exerciseId).map(x=>({date:s.date,session:s.name,sets:x.sets}))).sort((a,b)=>Date.parse(b.date)-Date.parse(a.date));
 const best=rows.flatMap(r=>r.sets.map(s=>({...s,date:r.date}))).sort((a,b)=>(Number(b.weight)*Number(b.reps))-(Number(a.weight)*Number(a.reps)))[0];
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.bg}]}><View style={styles.header}><ForgeBrand compact/><Pressable onPress={()=>router.back()}><Text style={[styles.close,{color:theme.muted}]}>BACK</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}><Text style={[styles.kicker,{color:theme.amber}]}>EXERCISE HISTORY</Text><Text style={[styles.h1,{color:theme.text}]}>{ex?.name||exerciseId}</Text><Text style={[styles.copy,{color:theme.muted}]}>{ex?.group} · {String(ex?.movement||'').replaceAll('_',' ')}</Text>{best&&<GlassCard><Text style={[styles.kicker,{color:theme.amber}]}>BEST MARK</Text><Text style={[styles.best,{color:theme.gold}]}>{best.weight} kg × {best.reps}</Text><Text style={[styles.micro,{color:theme.muted}]}>{shortDate(best.date)}</Text></GlassCard>}<View style={{gap:8}}>{rows.map((r,i)=><GlassCard key={`${r.date}-${i}`}><View style={styles.row}><Text style={[styles.date,{color:theme.text}]}>{shortDate(r.date)}</Text><Text style={[styles.micro,{color:theme.muted}]}>{r.session}</Text></View><View style={styles.sets}>{r.sets.map((s,j)=><Text key={j} style={[styles.set,{color:theme.gold}]}>{s.weight}×{s.reps}{s.rir!=null?` · ${s.rir} RIR`:''}</Text>)}</View></GlassCard>)}{!rows.length&&<Text style={[styles.copy,{color:theme.muted}]}>No logged exposures yet.</Text>}</View></ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1},header:{height:60,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{fontSize:8.5,fontWeight:'900',letterSpacing:1.2},content:{padding:16,paddingBottom:42,gap:13},kicker:{fontSize:8.5,fontWeight:'900',letterSpacing:1.4},h1:{fontSize:30,fontWeight:'1000',letterSpacing:-1.1},copy:{fontSize:10.5,lineHeight:16,fontWeight:'620'},best:{fontSize:28,fontWeight:'1000',marginTop:5},micro:{fontSize:8.5,fontWeight:'700'},row:{flexDirection:'row',justifyContent:'space-between',gap:10},date:{fontSize:13,fontWeight:'900'},sets:{flexDirection:'row',flexWrap:'wrap',gap:7,marginTop:12},set:{fontSize:9,fontWeight:'900'}});
