import React from 'react';
import {Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import {useRouter} from 'expo-router';
import {ForgeBrand} from '@/components/ForgeBrand';
import {GlassCard} from '@/components/GlassCard';
import {ForgeButton} from '@/components/ForgeButton';
import {useForge,exerciseMap} from '@/store/ForgeProvider';

const FOCUS=['Hypertrophy','Strength','Maintenance','Deload'];
export default function ProgrammeBuilder(){
 const router=useRouter();
 const {state,theme,getProgram,moveProgramExercise,removeProgramExercise,resetProgram,renameProgram,addTrainingBlock,updateTrainingBlock,duplicateTrainingBlock,removeTrainingBlock}=useForge();
 const p=getProgram(state.selectedProgramId);
 return <SafeAreaView style={[styles.safe,{backgroundColor:theme.bg}]}><View style={styles.header}><ForgeBrand compact/><Pressable onPress={()=>router.back()}><Text style={[styles.close,{color:theme.muted}]}>DONE</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>
  <Text style={[styles.kicker,{color:theme.amber}]}>PROGRAMME BUILDER 2.0</Text><Text style={[styles.h1,{color:theme.text}]}>Build the training system.</Text><Text style={[styles.copy,{color:theme.muted}]}>Reorder, replace and add exercises, then shape the block timeline. Changes stay local and are reversible.</Text>
  <GlassCard><Text style={[styles.label,{color:theme.muted}]}>PROGRAMME NAME</Text><TextInput value={p.name} onChangeText={x=>renameProgram(p.id,x)} style={[styles.input,{color:theme.text,borderColor:theme.line,backgroundColor:theme.panel2}]}/></GlassCard>
  <Text style={[styles.section,{color:theme.text}]}>Exercise order</Text>
  <View style={{gap:8}}>{p.exercises.map((id,i)=>{const ex=exerciseMap[id];return <GlassCard key={`${id}-${i}`} style={styles.exercise}><View style={{flex:1,minWidth:0}}><Text style={[styles.exerciseName,{color:theme.text}]}>{i+1}. {ex?.name||id}</Text><Text style={[styles.micro,{color:theme.muted}]}>{ex?.group} · {String(ex?.movement||'').replaceAll('_',' ')}</Text></View><View style={styles.actions}><Pressable onPress={()=>moveProgramExercise(p.id,i,-1)}><Text style={[styles.action,{color:i?theme.text:theme.muted}]}>↑</Text></Pressable><Pressable onPress={()=>moveProgramExercise(p.id,i,1)}><Text style={[styles.action,{color:i<p.exercises.length-1?theme.text:theme.muted}]}>↓</Text></Pressable><Pressable onPress={()=>router.push({pathname:'/exercise-picker',params:{mode:'programReplace',programId:p.id,index:String(i),exerciseId:id}})}><Text style={[styles.actionWord,{color:theme.gold}]}>SWAP</Text></Pressable><Pressable onPress={()=>removeProgramExercise(p.id,i)}><Text style={[styles.actionWord,{color:theme.muted}]}>REMOVE</Text></Pressable></View></GlassCard>})}</View>
  <ForgeButton label="Add exercise" onPress={()=>router.push({pathname:'/exercise-picker',params:{mode:'programAdd',programId:p.id}})} ghost/>
  <Text style={[styles.section,{color:theme.text}]}>Training blocks</Text>
  <View style={{gap:8}}>{p.blocks.map((b,i)=><GlassCard key={b.id}><View style={styles.row}><View style={{flex:1}}><Text style={[styles.exerciseName,{color:theme.text}]}>{i+1}. {b.name}</Text><Pressable onPress={()=>{const j=(FOCUS.indexOf(b.focus)+1)%FOCUS.length;updateTrainingBlock(p.id,b.id,{focus:FOCUS[j]})}}><Text style={[styles.focus,{color:theme.amber}]}>{b.focus.toUpperCase()} · TAP TO CHANGE</Text></Pressable></View><View style={styles.weekBox}><Pressable onPress={()=>updateTrainingBlock(p.id,b.id,{weeks:Math.max(1,b.weeks-1)})}><Text style={[styles.action,{color:theme.muted}]}>−</Text></Pressable><Text style={[styles.week,{color:theme.text}]}>{b.weeks}w</Text><Pressable onPress={()=>updateTrainingBlock(p.id,b.id,{weeks:Math.min(16,b.weeks+1)})}><Text style={[styles.action,{color:theme.amber}]}>+</Text></Pressable></View></View><View style={[styles.row,{marginTop:10}]}><Pressable onPress={()=>duplicateTrainingBlock(p.id,b.id)}><Text style={[styles.link,{color:theme.gold}]}>DUPLICATE</Text></Pressable><Pressable onPress={()=>removeTrainingBlock(p.id,b.id)}><Text style={[styles.link,{color:theme.muted}]}>REMOVE</Text></Pressable></View></GlassCard>)}</View>
  <ForgeButton label="Add training block" onPress={()=>addTrainingBlock(p.id)} ghost/>
  <ForgeButton label="Reset programme to original" onPress={()=>Alert.alert('Reset programme?','This removes your edits to this programme.',[{text:'Cancel',style:'cancel'},{text:'Reset',style:'destructive',onPress:()=>resetProgram(p.id)}])} ghost/>
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({safe:{flex:1},header:{height:60,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{fontSize:8.5,fontWeight:'900',letterSpacing:1.2},content:{padding:16,paddingBottom:42,gap:13},kicker:{fontSize:8.5,fontWeight:'900',letterSpacing:1.5},h1:{fontSize:30,fontWeight:'1000',letterSpacing:-1.1},copy:{fontSize:10.5,lineHeight:16,fontWeight:'620'},label:{fontSize:8,fontWeight:'900',letterSpacing:1.2,marginBottom:8},input:{borderWidth:1,borderRadius:13,paddingHorizontal:12,height:46,fontSize:15,fontWeight:'850'},section:{fontSize:18,fontWeight:'950',letterSpacing:-.4,marginTop:5},exercise:{flexDirection:'row',alignItems:'center',gap:10,padding:12},exerciseName:{fontSize:13,fontWeight:'900'},micro:{fontSize:8.5,fontWeight:'650',marginTop:4},actions:{flexDirection:'row',alignItems:'center',gap:9},action:{fontSize:20,fontWeight:'950',padding:2},actionWord:{fontSize:7,fontWeight:'900',letterSpacing:.5},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},focus:{fontSize:8,fontWeight:'900',letterSpacing:.7,marginTop:5},weekBox:{flexDirection:'row',alignItems:'center',gap:8},week:{fontSize:15,fontWeight:'950'},link:{fontSize:7.5,fontWeight:'900',letterSpacing:.8}});
