import React,{useEffect,useState} from 'react';
import { View,Text,StyleSheet,Pressable,ScrollView,Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { useForge,exerciseMap } from '@/store/ForgeProvider';
import { GlassCard } from '@/components/GlassCard';
import { ForgeButton } from '@/components/ForgeButton';
import { ForgeBrand } from '@/components/ForgeBrand';

function Stepper({label,value,onMinus,onPlus,suffix}:{label:string;value:number;onMinus:()=>void;onPlus:()=>void;suffix?:string}){
 const {theme}=useForge();return <View style={{flex:1}}><Text style={[styles.stepLabel,{color:theme.muted}]}>{label}</Text><View style={[styles.stepper,{borderColor:theme.line,backgroundColor:theme.panel2}]}><Pressable onPress={onMinus} style={styles.stepBtn}><Text style={[styles.stepSymbol,{color:theme.muted}]}>−</Text></Pressable><Text style={[styles.stepValue,{color:theme.text}]}>{value}{suffix||''}</Text><Pressable onPress={onPlus} style={styles.stepBtn}><Text style={[styles.stepSymbol,{color:theme.amber}]}>+</Text></Pressable></View></View>
}
export default function Workout(){
 const router=useRouter();
 const {state,theme,getProgram,adjustInput,addSet,nextExercise,finishWorkout,clearRestTimer,adjustRestTimer,setRestNotifications}=useForge();
 const [now,setNow]=useState(Date.now());
 useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t)},[]);
 useEffect(()=>{if(state.workout.restTimerEndsAt&&state.workout.restTimerEndsAt<=now)clearRestTimer()},[now,state.workout.restTimerEndsAt]);
 const p=getProgram(state.workout.programId),order=state.workout.exerciseOrder?.length?state.workout.exerciseOrder:p.exercises,idx=Math.min(state.workout.exerciseIndex,order.length-1),exId=order[idx],ex:any=exerciseMap[exId],sets=state.workout.exerciseSets[exId]||[],elapsed=state.workout.startedAt?Math.max(0,Math.round((Date.now()-state.workout.startedAt)/60000)):0;
 const previousSession=[...(state.sessions||[])].filter(s=>Number.isFinite(Date.parse(s.date||''))).sort((a,b)=>Date.parse(b.date||'')-Date.parse(a.date||'')).find(s=>(s.exercises||[]).some(e=>e.exerciseId===exId));
 const previousExercise=previousSession?.exercises?.find(e=>e.exerciseId===exId);const previous=previousExercise?.sets?.filter(s=>(s.setType||'working')!=='warmup').sort((a,b)=>(Number(b.weight||0)*Number(b.reps||0))-(Number(a.weight||0)*Number(a.reps||0)))[0];
 const target=previous?`${previous.weight} kg × ${previous.reps}`:'Establish baseline';
 const priorBest=(state.sessions||[]).filter(s=>Number.isFinite(Date.parse(s.date||''))).flatMap(s=>(s.exercises||[]).filter(e=>e.exerciseId===exId)).flatMap(e=>e.sets||[]).filter(s=>(s.setType||'working')!=='warmup').reduce((m,s)=>Math.max(m,Number(s.weight||0)*Number(s.reps||0)),0);const currentScore=Number(state.workout.input.weight||0)*Number(state.workout.input.reps||0),isPr=priorBest>0&&currentScore>priorBest;
 const adaptation=Math.max(.5,Math.min(1,Number(state.workout.adaptationFactor||1))),plannedSets=Math.max(1,Math.round(3*adaptation));
 const rest=Math.max(0,Math.ceil(((state.workout.restTimerEndsAt||0)-now)/1000));
 const totalLogged=Object.values(state.workout.exerciseSets).reduce((a:any,b:any)=>a+(b?.length||0),0),completedExercises=Object.values(state.workout.exerciseSets).filter((x:any)=>x?.length).length;
 const finish=()=>Alert.alert('Finish workout?',`${totalLogged} sets across ${completedExercises} exercise${completedExercises===1?'':'s'} logged`,[{text:'Keep training',style:'cancel'},{text:'Finish',onPress:()=>{finishWorkout();router.back()}}]);
 const enableAlerts=async()=>{const ok=await setRestNotifications(true);Alert.alert('Rest alerts',ok?'Background rest-complete alerts are enabled.':'Notification permission was not granted.')};
 return <SafeAreaView edges={['top','bottom']} style={[styles.safe,{backgroundColor:theme.bg}]}><View style={styles.header}><ForgeBrand compact/><Pressable onPress={()=>router.back()}><Text style={[styles.close,{color:theme.muted}]}>MINIMIZE</Text></Pressable></View><ScrollView contentContainerStyle={styles.content}>
   <View style={styles.topline}><Text style={[styles.kicker,{color:theme.amber}]}>{p.name.toUpperCase()}</Text><Text style={[styles.kicker,{color:theme.muted}]}>{elapsed} MIN · {idx+1}/{order.length}</Text></View>
   <Text style={[styles.exercise,{color:theme.text}]}>{ex?.name||'Exercise'}</Text><Text style={[styles.meta,{color:theme.muted}]}>{ex?.group} · {String(ex?.movement||'').replaceAll('_',' ')}</Text>
   <Pressable onPress={()=>router.push({pathname:'/exercise-picker',params:{mode:'workout',exerciseId:exId}})}><Text style={[styles.swap,{color:theme.gold}]}>SWAP EXERCISE · SMART MATCHES ›</Text></Pressable>
   {adaptation<1&&<View style={[styles.adapted,{borderColor:theme.amber}]}><View><Text style={[styles.kicker,{color:theme.gold}]}>ADAPTED SESSION · {Math.round(adaptation*100)}%</Text><Text style={[styles.adaptedCopy,{color:theme.muted}]}>You accepted reduced working volume. The permanent programme is unchanged.</Text></View><Text style={[styles.adaptedTarget,{color:theme.text}]}>{plannedSets} SET TARGET</Text></View>}<View style={[styles.liveRail,{borderColor:theme.line}]}><View><Text style={[styles.liveLabel,{color:theme.muted}]}>LIVE SET</Text><Text style={[styles.liveValue,{color:theme.text}]}>{sets.length+1}</Text></View><View><Text style={[styles.liveLabel,{color:theme.muted}]}>REST</Text><Text style={[styles.liveValue,{color:rest>0?theme.amber:theme.text}]}>{rest>0?`${Math.floor(rest/60)}:${String(rest%60).padStart(2,'0')}`:'READY'}</Text></View><View><Text style={[styles.liveLabel,{color:theme.muted}]}>ELAPSED</Text><Text style={[styles.liveValue,{color:theme.text}]}>{elapsed}m</Text></View></View>
   <View style={[styles.targetRail,{borderColor:theme.line}]}><View><Text style={[styles.liveLabel,{color:theme.muted}]}>PREVIOUS</Text><Text style={[styles.targetValue,{color:theme.text}]}>{target}</Text></View><View style={{alignItems:'flex-end'}}><Text style={[styles.liveLabel,{color:theme.muted}]}>TODAY</Text><Text style={[styles.targetValue,{color:theme.gold}]}>{state.workout.input.weight} kg × {state.workout.input.reps}</Text></View></View>
   <View style={styles.steppers}><Stepper label="WEIGHT" value={Number(state.workout.input.weight||0)} suffix="kg" onMinus={()=>adjustInput('weight',-1)} onPlus={()=>adjustInput('weight',1)}/><Stepper label="REPS" value={Number(state.workout.input.reps||0)} onMinus={()=>adjustInput('reps',-1)} onPlus={()=>adjustInput('reps',1)}/><Stepper label="RIR" value={Number(state.workout.input.rir||0)} onMinus={()=>adjustInput('rir',-1)} onPlus={()=>adjustInput('rir',1)}/></View>
   {isPr&&<View style={[styles.prRail,{borderColor:theme.amber}]}><Text style={[styles.kicker,{color:theme.gold}]}>PR RANGE</Text><Text style={[styles.prText,{color:theme.text}]}>This set would exceed your recorded best load × reps for {ex?.name||'this exercise'}.</Text></View>}<ForgeButton label={isPr?`Log PR set ${sets.length+1}`:`Log set ${sets.length+1}`} onPress={addSet}/>{adaptation<1&&sets.length>=plannedSets&&<Text style={[styles.volumeDone,{color:theme.gold}]}>ADAPTED VOLUME TARGET REACHED · MOVE ON WHEN READY</Text>}
   {rest>0&&<GlassCard style={[styles.restCard,{borderColor:theme.amber}]}><View style={styles.row}><View><Text style={[styles.kicker,{color:theme.amber}]}>REST TIMER</Text><Text style={[styles.restValue,{color:theme.text}]}>{Math.floor(rest/60)}:{String(rest%60).padStart(2,'0')}</Text></View><View style={styles.restActions}><Pressable onPress={()=>adjustRestTimer(30)}><Text style={[styles.restBtn,{color:theme.gold,borderColor:theme.line}]}>+30s</Text></Pressable><Pressable onPress={clearRestTimer}><Text style={[styles.restBtn,{color:theme.muted,borderColor:theme.line}]}>SKIP</Text></Pressable></View></View>{!state.settings.restNotifications&&<Pressable onPress={enableAlerts}><Text style={[styles.alertLink,{color:theme.gold}]}>ENABLE BACKGROUND REST ALERTS</Text></Pressable>}</GlassCard>}
   <GlassCard><Text style={[styles.kicker,{color:theme.amber}]}>SETS THIS EXERCISE</Text><View style={{gap:8,marginTop:12}}>{sets.map((s:any,i:number)=><View key={i} style={[styles.setRow,{borderColor:theme.line}]}><Text style={[styles.setNum,{color:theme.muted}]}>SET {i+1}</Text><Text style={[styles.setText,{color:theme.text}]}>{s.weight} kg × {s.reps}</Text><Text style={[styles.setRir,{color:theme.gold}]}>{s.rir ?? '—'} RIR</Text></View>)}{!sets.length&&<Text style={[styles.meta,{color:theme.muted}]}>No sets logged yet.</Text>}</View></GlassCard>
   <GlassCard><Text style={[styles.kicker,{color:theme.amber}]}>UP NEXT</Text><Text style={[styles.next,{color:theme.text}]}>{idx<order.length-1?exerciseMap[order[idx+1]]?.name:'Workout complete'}</Text><Text style={[styles.meta,{color:theme.muted}]}>{idx<order.length-1?'Carry momentum. Keep technique clean.':'Save the session to your training history.'}</Text></GlassCard>
   {idx<order.length-1?<ForgeButton label="Next exercise" onPress={nextExercise} ghost/>:<ForgeButton label="Finish workout" onPress={finish}/>}<Pressable onPress={finish}><Text style={[styles.end,{color:theme.muted}]}>End workout now · {totalLogged} sets saved on finish</Text></Pressable>
 </ScrollView></SafeAreaView>
}
const styles=StyleSheet.create({adapted:{borderLeftWidth:2,paddingLeft:11,paddingVertical:7,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},adaptedCopy:{fontSize:9,lineHeight:13,fontWeight:'600',marginTop:3,maxWidth:240},adaptedTarget:{fontSize:9,fontWeight:'900'},volumeDone:{fontSize:8,fontWeight:'900',letterSpacing:.7,textAlign:'center'},prRail:{borderTopWidth:1,borderBottomWidth:1,paddingVertical:10,gap:4},prText:{fontSize:10,lineHeight:14,fontWeight:'700'},safe:{flex:1},header:{height:60,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},close:{fontSize:8.5,fontWeight:'900',letterSpacing:1.2},content:{padding:16,paddingBottom:40,gap:15},targetRail:{borderBottomWidth:1,paddingBottom:10,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},targetValue:{fontSize:12,fontWeight:'900',marginTop:4},liveRail:{minHeight:62,borderTopWidth:1,borderBottomWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingVertical:10,paddingHorizontal:2},liveLabel:{fontSize:7,fontWeight:'900',letterSpacing:1.2},liveValue:{fontSize:17,fontWeight:'900',letterSpacing:-.5,marginTop:3},topline:{flexDirection:'row',justifyContent:'space-between',gap:10},kicker:{fontSize:8.5,fontWeight:'900',letterSpacing:1.4},exercise:{fontSize:31,lineHeight:33,fontWeight:'900',letterSpacing:-1.2},meta:{fontSize:10.5,lineHeight:15,fontWeight:'600'},swap:{fontSize:8,fontWeight:'900',letterSpacing:.8,marginTop:-5},steppers:{flexDirection:'row',gap:8},stepLabel:{fontSize:7.5,fontWeight:'900',letterSpacing:1.2,marginBottom:5},stepper:{height:92,borderWidth:1,borderRadius:16,alignItems:'center',justifyContent:'space-between',paddingVertical:5},stepBtn:{height:22,width:'100%',alignItems:'center',justifyContent:'center'},stepSymbol:{fontSize:20,fontWeight:'900'},stepValue:{fontSize:18,fontWeight:'900',letterSpacing:-.5},setRow:{flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,paddingVertical:9},setNum:{fontSize:8,fontWeight:'900',width:42},setText:{fontSize:13,fontWeight:'900',flex:1},setRir:{fontSize:9,fontWeight:'900'},next:{fontSize:18,fontWeight:'900',marginTop:8},end:{textAlign:'center',fontSize:9,fontWeight:'800',padding:8},restCard:{gap:10},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},restValue:{fontSize:31,fontWeight:'900',letterSpacing:-1,marginTop:4},restActions:{flexDirection:'row',gap:7},restBtn:{fontSize:8,fontWeight:'900',borderWidth:1,borderRadius:10,paddingHorizontal:10,paddingVertical:8},alertLink:{fontSize:7.5,fontWeight:'900',letterSpacing:.7}});
