'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { STAGE_LABELS, type WorkItem } from '@concord/shared';
import { getWork, getObligations } from '@/app/lib/api';
import { errorMessage, RequestError, RequestLoading, requestDate } from '@/components/RequestUI';
import { IconArrowRight, IconSearch } from '@/components/icons';
const TABS = [['all','All'],['intake','Requests'],['drafting','Drafting'],['review','Review'],['negotiation','Negotiation'],['approval','Approvals'],['signature','Signature'],['obligations','Obligations']];
export default function WorkPage() {
  const [items, setItems] = useState<WorkItem[]>();
  const [total, setTotal] = useState(0);
  const [stage, setStage] = useState('all');
  const [view, setView] = useState('all');
  const [query, setQuery] = useState('');
  const [risk, setRisk] = useState('');
  const [unit, setUnit] = useState('');
  const [type, setType] = useState('');
  const [priority, setPriority] = useState('');
  const [due, setDue] = useState('');
  const [dates, setDates] = useState<Record<string,string>>({});
  const [error, setError] = useState('');
  const [dateError, setDateError] = useState('');
  const load = useCallback(async () => { setError(''); try { const data = await getWork(view); setItems(data.items); setTotal(data.total); } catch (e) { setError(errorMessage(e)); } }, [view]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const s = new URLSearchParams(window.location.search).get('stage'); if (TABS.some(t => t[0] === s)) setStage(s!); getObligations().then(rows => { const map: Record<string,string> = {}; for (const o of rows) if (!map[o.contractId] || o.dueDate < map[o.contractId]) map[o.contractId] = o.dueDate; setDates(map); }).catch(() => setDateError('Key dates could not be loaded. Obligation counts may be incomplete; refresh to try again.')); }, []);
  const all = useMemo(() => (items ?? []).map(item => ({ ...item, dueDate: ['active','renewal'].includes(item.stage) ? dates[item.id] : item.dueDate })), [items, dates]);
  const inStage = (item: WorkItem, s: string) => s === 'all' ? !['active','renewal'].includes(item.stage) || !!dates[item.id] : s === 'obligations' ? ['active','renewal'].includes(item.stage) && !!dates[item.id] : s === 'approval' ? ['approval','agreed'].includes(item.stage) : item.stage === s;
  const rows = all.filter(item => inStage(item, stage) && (!risk || item.risk === risk) && (!unit || item.businessUnit === unit) && (!type || item.type === type) && (!priority || item.priority === priority) && (!due || !!item.dueDate && Date.parse(item.dueDate) <= Date.now() + Number(due) * 86400000) && `${item.title} ${item.counterparty} ${item.requestId ?? ''} ${item.ownerName ?? ''}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b) => (a.dueDate ?? '9999').localeCompare(b.dueDate ?? '9999') || Number(b.priority === 'urgent') - Number(a.priority === 'urgent'));
  return <div className="work-page"><div className="view-head"><div className="vh-left"><div className="eyebrow">Your legal workspace</div><h2>Move the work forward.</h2><p>One agreement. Every stage. A clear next action.</p></div><label className="work-scope"><span className="sr-only">Work scope</span><select value={view} onChange={e => setView(e.target.value)}><option value="all">My team</option><option value="mine">Assigned to me</option></select></label></div>
  {dateError && <RequestError message={dateError} />}<nav className="lifecycle-filters" aria-label="Filter work by stage">{TABS.map(([key,label]) => <button key={key} aria-pressed={stage === key} onClick={() => setStage(key)}>{label}<span>{items && !(dateError && key === 'obligations') ? all.filter(i => inStage(i,key)).length : '—'}</span></button>)}</nav>
  <div className="work-controls"><label className="work-search"><IconSearch /><span className="sr-only">Find an agreement</span><input type="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="Find an agreement, counterparty or owner" /></label><details className="work-filter-menu"><summary className="btn">Filters{[risk,unit,type,priority,due].filter(Boolean).length ? ` · ${[risk,unit,type,priority,due].filter(Boolean).length}` : ''}</summary><div className="req-fields"><label className="req-field">Risk<select value={risk} onChange={e => setRisk(e.target.value)}><option value="">All risks</option>{['low','medium','high'].map(r => <option key={r}>{r}</option>)}</select></label><label className="req-field">Business unit<select value={unit} onChange={e => setUnit(e.target.value)}><option value="">All business units</option>{[...new Set(all.map(r => r.businessUnit).filter(Boolean))].map(u => <option key={u}>{u}</option>)}</select></label><label className="req-field">Agreement type<select value={type} onChange={e => setType(e.target.value)}><option value="">All types</option>{[...new Set(all.map(r => r.type))].map(t => <option key={t}>{t}</option>)}</select></label><label className="req-field">Priority<select value={priority} onChange={e => setPriority(e.target.value)}><option value="">Any priority</option><option value="urgent">Urgent</option><option value="standard">Standard</option></select></label><label className="req-field">Due<select value={due} onChange={e => setDue(e.target.value)}><option value="">Any time</option><option value="0">Overdue</option><option value="7">Within 7 days</option><option value="30">Within 30 days</option></select></label><button className="btn" onClick={() => { setRisk(''); setUnit(''); setType(''); setPriority(''); setDue(''); }}>Clear filters</button></div></details></div>
  {error ? <RequestError message={error} retry={load} /> : !items ? <RequestLoading /> : <><div className="work-count">{rows.length} agreements{total > items.length ? ` · latest ${items.length} of ${total}; use Contracts search for the full portfolio` : ''}</div><div className="work-list">{rows.map(item => <Link className="work-card" key={item.id} href={`/contracts/${encodeURIComponent(item.id)}`}><div className="work-card-title"><span className="req-id">{item.requestId ?? item.type}</span><h3>{item.title}</h3><p>{item.counterparty}{item.businessUnit ? ` · ${item.businessUnit}` : ''}</p></div><div className="work-card-stage"><span className={`badge ${item.risk === 'medium' ? 'med' : item.risk}`}>{STAGE_LABELS[item.stage]}</span><small>{item.risk} risk{item.priority === 'urgent' ? ' · Urgent' : ''}</small></div><div className="work-card-next"><small>Next action</small><b>{item.nextAction}</b><span>{item.waitingOn || (item.waitingOnClient ? item.businessOwner : item.ownerName || 'Legal team')}</span></div><div className="work-card-due"><small>Target date</small><b>{item.dueDate ? requestDate(item.dueDate) : 'Not set'}</b></div><IconArrowRight /></Link>)}</div>{!rows.length && <div className="req-empty"><h3>Nothing needs attention in this view.</h3><p>Try another stage or clear your filters.</p><button className="btn" onClick={() => { setStage('all'); setQuery(''); setRisk(''); setUnit(''); setType(''); setPriority(''); setDue(''); }}>Show all work</button></div>}</>}
  </div>;
}
