'use client';
import { useCallback, useEffect, useState } from 'react';
import { AgreementWorkspace, NegotiationWorkspace } from '@concord/shared';
import { getNegotiation, inviteCounterparty, actOnNegotiation, getAgreementWorkspace, resolveAgreementComment } from '@/app/lib/api';
import { errorMessage, RequestError, RequestLoading, requestDate } from './RequestUI';
import DocumentComparison from './DocumentComparison';
export default function AgreementNegotiation({ data, onChange, onEdit }: { data: AgreementWorkspace; onChange: (d: AgreementWorkspace) => void; onEdit: () => void }) {
  const [workspace,setWorkspace] = useState<NegotiationWorkspace>(), [error,setError] = useState(''), [busy,setBusy] = useState(false), [inviting,setInviting] = useState(false), [preview,setPreview] = useState(false);
  const [name,setName] = useState(''), [email,setEmail] = useState(''), [organisation,setOrganisation] = useState(data.contract.counterparty), [expires,setExpires] = useState(() => new Date(Date.now()+14*86400000).toISOString().slice(0,10)), [due,setDue] = useState('');
  const [download,setDownload] = useState(false), [redline,setRedline] = useState(true), [upload,setUpload] = useState(true), [externalComment,setExternalComment] = useState(''), [invitationId,setInvitationId] = useState(() => crypto.randomUUID());
  const id = data.contract.id, document = data.documents.find(d => d.hasFile && d.status !== 'quarantined');
  const load = useCallback(async () => { setError(''); try { setWorkspace(await getNegotiation(id)); } catch(e) { setError(errorMessage(e)); } },[id]);
  useEffect(() => { void load(); },[load]);
  async function run(fn: () => Promise<NegotiationWorkspace>) { if (busy) return; setBusy(true); setError(''); try { setWorkspace(await fn()); onChange(await getAgreementWorkspace(id)); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  const pin = { revision: data.revision, documentId: document?.id };
  const writable = ['review','negotiation'].includes(data.contract.stage) && !data.approval;
  const activeGuests = workspace?.invitations.filter(i => !i.revokedAt && Date.parse(i.expiresAt) > Date.now()) ?? [];
  const comments = (data.comments ?? []).filter(c => !c.resolvedAt);
  return <div className="negotiation-workspace">
    <section className="card card-pad"><div className="agreement-section-head"><div><span className="section-kicker">One agreement · controlled exchange</span><h3>Counterparty negotiation</h3></div>{workspace && <span className="badge neutral">{workspace.rounds.length} shared rounds</span>}</div>
      <p className="req-help">Share a specific saved draft, review counterparty changes here and confirm the exact agreed form.</p>{error && <RequestError message={error} retry={load} />}{!workspace && !error && <RequestLoading />}
      {workspace && !workspace.emailConfigured && <p className="editor-notice">Microsoft email delivery is not configured. Invitations can be prepared, but guests cannot receive their invitation or verification code until email is connected.</p>}
      {writable && <div className="req-actions"><button className="btn btn-gold" disabled={busy || !document} onClick={() => { setInviting(!inviting); setPreview(false); }}>Share with Counterparty</button>{!!activeGuests.length && <button className="btn" disabled={busy || !document} onClick={() => void run(() => actOnNegotiation(id,'share',pin))}>Share current version with active guests</button>}<button className="btn" onClick={onEdit}>Edit Agreement</button></div>}
      {inviting && writable && <form className="req-form invitation-form" onSubmit={e => { e.preventDefault(); if (!preview) { setPreview(true); return; } void run(async () => { const next = await inviteCounterparty(id,{ id: invitationId, revision: data.revision, documentId: document!.id, name, email, organisation, expiresAt: new Date(`${expires}T23:59:59Z`).toISOString(), responseDueAt: due ? new Date(`${due}T23:59:59Z`).toISOString() : undefined, allowDownload: download, allowRedline: redline, allowUpload: upload }); setInviting(false); setPreview(false); setInvitationId(crypto.randomUUID()); return next; }); }}>
      {preview ? <section className="invitation-preview"><span className="section-kicker">Review secure invitation</span><h3>{name} · {organisation}</h3><p>{email}</p><dl className="agreement-facts"><div><dt>Document</dt><dd>{data.contract.version} · {document?.filename}</dd></div><div><dt>Access expires</dt><dd>{expires}</dd></div><div><dt>Response due</dt><dd>{due || 'Not specified'}</dd></div><div><dt>Allowed actions</dt><dd>Read and comment{download ? ', download' : ''}{redline ? ', suggest changes' : ''}{upload ? ', upload Word redline' : ''}</dd></div></dl><p className="req-help">Only the saved document and deliberately shared external comments appear in the review room. The guest verifies their invited email using a one-time code.</p><details className="workflow-disclosure"><summary>Preview shared document text</summary>{data.draft?.sections.map((s,i) => <section className="shared-clause" key={s.id ?? i}>{s.kind !== 'paragraph' && <h4>{s.heading}</h4>}<p>{s.body}</p></section>)}</details><button className="btn" type="button" onClick={() => setPreview(false)}>Edit invitation</button></section> : <><div className="req-fields"><label className="req-field">Participant name<input required maxLength={160} value={name} onChange={e => setName(e.target.value)} /></label><label className="req-field">Email<input required type="email" autoComplete="off" maxLength={254} value={email} onChange={e => setEmail(e.target.value)} /></label><label className="req-field">Organisation<input required maxLength={180} value={organisation} onChange={e => setOrganisation(e.target.value)} /></label><label className="req-field">Access expiry<input required type="date" value={expires} onChange={e => setExpires(e.target.value)} /></label><label className="req-field">Response deadline<input type="date" value={due} max={expires} onChange={e => setDue(e.target.value)} /></label></div><div className="guest-permissions"><label><input type="checkbox" checked={download} onChange={e => setDownload(e.target.checked)} />Allow document download</label><label><input type="checkbox" checked={redline} onChange={e => setRedline(e.target.checked)} />Allow suggested changes</label><label><input type="checkbox" checked={upload} onChange={e => setUpload(e.target.checked)} />Allow Word redline upload</label></div></>}
      <button className="btn btn-gold" disabled={busy || !document}>{busy ? 'Preparing invitation…' : preview ? 'Send Secure Invitation' : 'Review invitation →'}</button></form>}
      <div className="guest-list">{workspace?.invitations.map(i => <article key={i.id}><div><b>{i.name}</b><p>{i.organisation} · {i.email}</p><small>Expires {requestDate(i.expiresAt)} · Email: {i.deliveries[0]?.status ?? 'Not queued'}</small></div><span className="badge neutral">{i.revokedAt ? 'Revoked' : Date.parse(i.expiresAt) <= Date.now() ? 'Expired' : i.acceptedDocumentId ? 'Accepted shared draft' : i.viewedAt ? 'Viewed' : 'Invited'}</span>{!i.revokedAt && <button className="btn" disabled={busy} onClick={() => void run(() => actOnNegotiation(id,`invitations/${i.id}/revoke`))}>Revoke access</button>}</article>)}</div>
    </section>
    {workspace?.responses.map(r => <section className="card card-pad" key={r.id}><div className="agreement-section-head"><div><span className="section-kicker">Round {r.round.number} · {r.invitation.organisation}</span><h3>{r.invitation.name}’s response</h3></div><span className="badge neutral">{r.state}</span></div><p className="req-help">{r.changes.length} clause changes received {requestDate(r.createdAt)}. Risk analysis remains inside Legal review.</p><details className="workflow-disclosure"><summary>Compare received changes</summary><DocumentComparison before={r.originalSections} after={r.sections} /></details><div className="req-actions"><a className="btn" href={`/api/documents/${r.documentId}/file`}>Download submitted file</a>{r.state === 'received' && <><button className="btn btn-gold" onClick={onEdit}>Resolve in Edit Agreement</button><button className="btn" disabled={busy || document?.id === r.documentId} onClick={() => void run(() => actOnNegotiation(id,`responses/${r.id}/reviewed`,pin))}>Confirm saved Legal response</button></>}</div></section>)}
    {!!workspace?.rounds.length && <section className="card card-pad"><h3>Discussion and agreed form</h3>{comments.map(c => <article className="negotiation-comment" key={c.id}><span className="badge neutral">{c.visibility === 'internal' ? 'Internal only' : 'Shared externally'}</span><b>{c.authorName}</b><p>{c.body}</p><button className="btn" disabled={busy} onClick={async () => { setBusy(true); setError(''); try { onChange(await resolveAgreementComment(id,c.id,true)); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>Mark resolved</button></article>)}{data.contract.stage === 'negotiation' && <><form className="req-form" onSubmit={e => { e.preventDefault(); void run(async () => { const next = await actOnNegotiation(id,'comments',{ id: crypto.randomUUID(), documentId: workspace.rounds[0].documentId, body: externalComment }); setExternalComment(''); return next; }); }}><label className="req-field">External message<textarea required rows={3} maxLength={6000} value={externalComment} onChange={e => setExternalComment(e.target.value)} placeholder="This message is visible to invited counterparties." /></label><button className="btn" disabled={busy || !externalComment.trim()}>Share external message</button></form><div className="editor-notice"><h3>Ready for agreed form?</h3><p>Concord checks the exact document, counterparty acceptance, outstanding comments, business questions and the final review before freezing this version.</p><button className="btn btn-gold" disabled={busy || !document || !!comments.length || !activeGuests.length || activeGuests.some(i => i.acceptedDocumentId !== document.id)} onClick={() => void run(() => actOnNegotiation(id,'agreed',pin))}>Mark as Agreed Form</button></div></>}</section>}
  </div>;
}
