'use client';
import { useEffect, useState } from 'react';
import { AgreementWorkspace, DraftSection, Template } from '@concord/shared';
import { getTemplates, getAgreementWorkspace, startAgreementDraft, saveAgreementDraft, changeAgreementStage, uploadFiles, reviseAgreement } from '@/app/lib/api';
import { errorMessage, RequestError, TermSheet } from './RequestUI';
export default function AgreementDraft({ data, onChange }: { data: AgreementWorkspace; onChange: (data: AgreementWorkspace) => void }) {
  const [templates,setTemplates] = useState<Template[]>([]); const [templateId,setTemplateId] = useState(data.draft?.templateId ?? ''); const [sections,setSections] = useState<DraftSection[]>(data.draft?.sections ?? []); const [error,setError] = useState(''); const [busy,setBusy] = useState(false); const [dirty,setDirty] = useState(false);
  useEffect(() => { getTemplates().then(rows => { setTemplates(rows); setTemplateId(id => id || rows.find(t => t.contractType === data.contract.type)?.id || rows[0]?.id || ''); }).catch(e => setError(errorMessage(e))); }, [data.contract.type]);
  const locked = !!data.approval || ['signature','active','renewal'].includes(data.contract.stage);
  const [reason,setReason] = useState('');
  const canRevise = ['rejected','changes-requested'].includes(data.approval?.decision ?? '');
  async function action(kind: 'start' | 'save' | 'review') { if (busy) return; setBusy(true); setError(''); try { const next = kind === 'start' ? await startAgreementDraft(data.contract.id, { templateId, revision: data.revision }) : kind === 'save' ? await saveAgreementDraft(data.contract.id, { templateId, sections, revision: data.revision }) : await changeAgreementStage(data.contract.id,{ stage: 'review', revision: data.revision }); onChange(next); setSections(next.draft?.sections ?? []); setDirty(false); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  return <div className="agreement-draft"><section className="card card-pad"><div className="agreement-section-head"><h3>Drafting</h3><span className="req-id">{data.contract.version}{dirty ? ' · Unsaved changes' : ''}</span></div>{data.request && <details className="workflow-disclosure"><summary>Business instructions <span>Use the terms already provided</span></summary><TermSheet terms={data.request.terms} /></details>}
  {canRevise && <form className="req-form" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); setError(''); try { onChange(await reviseAgreement(data.contract.id,{ reason, revision: data.revision })); setReason(''); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }}><p className="req-note">Changes are required. Start a new revision to edit the draft and request fresh approvals. The previous document, comments and decisions remain in Versions.</p><label className="req-field">Revision note<textarea required maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} rows={2} /></label><button className="btn btn-gold" disabled={busy}>Start new revision</button></form>}
  {!locked && !sections.length && <div className="req-fields"><label className="req-field wide">Approved template<select value={templateId} onChange={e => setTemplateId(e.target.value)}><option value="">Choose a template</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name} · {t.contractType}</option>)}</select></label><button className="btn btn-gold" disabled={busy || !templateId} onClick={() => void action('start')}>{busy ? 'Preparing draft…' : 'Create from approved template'}</button><label className="req-field wide">Or upload counterparty paper<input type="file" accept=".pdf,.docx,.txt" disabled={busy} onChange={async e => { const f = e.target.files?.[0]; if (!f) return; setBusy(true); setError(''); try { const result = await uploadFiles([f], data.contract.id); if (result.some(r => r.status === 'quarantined')) throw new Error('The document was quarantined. Review the file before trying again.'); const saved = await getAgreementWorkspace(data.contract.id); const next = await changeAgreementStage(data.contract.id, { stage: 'review', revision: saved.revision }); onChange(next); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }} /><small>Saved to this agreement; earlier documents stay in Versions.</small></label></div>}
  {sections.map((s,i) => <section className="draft-section" key={i}><label className="req-field"><span className="sr-only">Section {i + 1} heading</span><input maxLength={500} readOnly={locked} value={s.heading} onChange={e => { setSections(rows => rows.map((r,j) => j === i ? { ...r, heading: e.target.value } : r)); setDirty(true); }} /></label><label className="req-field"><span className="sr-only">{s.heading} language</span><textarea maxLength={50000} rows={Math.min(12, Math.max(4,Math.ceil(s.body.length/120)))} readOnly={locked} value={s.body} onChange={e => { setSections(rows => rows.map((r,j) => j === i ? { ...r, body: e.target.value } : r)); setDirty(true); }} /></label></section>)}
  {!!sections.length && !locked && <button className="btn" onClick={() => { setSections(rows => [...rows,{ heading: `Clause ${rows.length + 1}`, body: '' }]); setDirty(true); }} disabled={busy || sections.length >= 100}>Add clause</button>}{locked && <p className="req-note">This version is locked to its approval and signing evidence.</p>}{error && <RequestError message={error} />}
  {!!sections.length && !locked && <div className="req-actions sticky-context"><button className="btn" disabled={busy || !dirty} onClick={() => void action('save')}>{busy ? 'Saving…' : 'Save draft version'}</button>{data.draft?.documentId && <a className="btn" href={`/api/documents/${data.draft.documentId}/file`}>Download Word</a>}<button className="btn btn-gold" disabled={busy || dirty} onClick={() => void action('review')}>Continue to review →</button></div>}
  <p className="req-help">Draft language remains under your control. Check clauses against the business instructions before requesting approval.</p></section></div>;
}
