'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { AgreementWorkspace, Clause, DraftSection, Template } from '@concord/shared';
import { getTemplates, getClauses, getAgreementWorkspace, startAgreementDraft, saveAgreementDraft, changeAgreementStage, uploadFiles, reviseAgreement, getAgreementEditor, AgreementEditorSource, addAgreementComment, resolveAgreementComment, rewriteAgreementSection } from '@/app/lib/api';
import { errorMessage, RequestError, RequestLoading, TermSheet } from './RequestUI';
import DocumentComparison from './DocumentComparison';

const identify = (rows: DraftSection[]) => rows.map((row,i) => ({ ...row, id: row.id ?? `section-${i}` }));
export default function AgreementDraft({ data, onChange, onDirtyChange }: { data: AgreementWorkspace; onChange: (data: AgreementWorkspace) => void; onDirtyChange?: (dirty: boolean) => void }) {
  const [templates,setTemplates] = useState<Template[]>([]), [clauses,setClauses] = useState<Clause[]>([]);
  const [templateId,setTemplateId] = useState(data.draft?.templateId ?? ''), [clauseId,setClauseId] = useState('');
  const [source,setSource] = useState<AgreementEditorSource>(), [sections,setSections] = useState<DraftSection[]>([]);
  const [active,setActive] = useState(0), [error,setError] = useState(''), [busy,setBusy] = useState(''), [notice,setNotice] = useState('');
  const [reason,setReason] = useState(''), [compare,setCompare] = useState(false), [reviewedTracked,setReviewedTracked] = useState(false), [comment,setComment] = useState('');
  const [instruction,setInstruction] = useState(''), [proposal,setProposal] = useState<{ body: string; model: string; id: string; before: string }>();
  const [conflict,setConflict] = useState<{ data: AgreementWorkspace; source: AgreementEditorSource }>(), [checkedConflict,setCheckedConflict] = useState(false);
  const history = useRef<{ past: DraftSection[][]; future: DraftSection[][]; at: number }>({ past: [], future: [], at: 0 });
  const locked = !!data.approval || ['signature','active','renewal','agreed'].includes(data.contract.stage);
  const canRevise = ['approved','rejected','changes-requested'].includes(data.approval?.decision ?? '') || data.contract.stage === 'agreed';
  const dirty = !!source && JSON.stringify(sections) !== JSON.stringify(identify(source.sections));
  const selected = sections[active];
  function install(next: AgreementEditorSource) { setSource(next); setSections(identify(next.sections)); setCompare(next.trackedChanges); setReviewedTracked(false); setActive(0); history.current = { past: [], future: [], at: 0 }; setProposal(undefined); }
  const load = useCallback(async () => { setError(''); try { install(await getAgreementEditor(data.contract.id)); } catch(e) { setError(errorMessage(e)); } }, [data.contract.id]);
  useEffect(() => { void load(); Promise.all([getTemplates(),getClauses()]).then(([ts,cs]) => { setTemplates(ts); setClauses(cs); setTemplateId(id => id || ts.find(t => t.contractType === data.contract.type)?.id || ts[0]?.id || ''); }).catch(e => setError(errorMessage(e))); }, [load, data.contract.type]);
  useEffect(() => { onDirtyChange?.(dirty); }, [dirty, onDirtyChange]);
  useEffect(() => {
    if (!dirty) return;
    const unload = (e: BeforeUnloadEvent) => { e.preventDefault(); e.returnValue = ''; };
    const leave = (e: MouseEvent) => { const link = (e.target as HTMLElement).closest('a[href]') as HTMLAnchorElement | null; if (link && !link.pathname.startsWith('/api/') && !link.download && link.target !== '_blank' && !window.confirm('Leave without saving this draft?')) { e.preventDefault(); e.stopPropagation(); } };
    window.addEventListener('beforeunload',unload); document.addEventListener('click',leave,true);
    return () => { window.removeEventListener('beforeunload',unload); document.removeEventListener('click',leave,true); };
  }, [dirty]);
  function update(next: DraftSection[], coalesce = false) {
    if (!coalesce || Date.now() - history.current.at > 700) history.current.past = [...history.current.past.slice(-24), sections];
    history.current.at = Date.now(); history.current.future = []; setSections(next); setNotice('');
  }
  function undo(redo = false) { const h = history.current, list = redo ? h.future : h.past; const next = list.pop(); if (!next) return; (redo ? h.past : h.future).push(sections); setSections(next); setActive(i => Math.max(0, Math.min(i, next.length - 1))); h.at = 0; }
  function edit(part: Partial<DraftSection>) { update(sections.map((s,i) => i === active ? { ...s, ...part } : s),true); }
  async function run(kind: string, fn: () => Promise<void>) { if (busy) return; setBusy(kind); setError(''); try { await fn(); } catch(e) { setError(errorMessage(e)); } finally { setBusy(''); } }
  async function save(prepareExternalCopy = false) {
    const next = await saveAgreementDraft(data.contract.id,{ prepareExternalCopy, confirmTrackedChanges: reviewedTracked, templateId: templateId || undefined, sections, revision: source!.revision, reason: reason || 'Legal document edits', sourceDocumentId: source?.documentId ?? undefined });
    onChange(next); install(await getAgreementEditor(data.contract.id)); setReason(''); setNotice(`${next.contract.version} saved. Previous versions are preserved.`);
  }
  function restore(id: string) {
    const baseline = identify(source?.original ?? []), old = baseline.find(s => s.id === id), index = sections.findIndex(s => s.id === id);
    if (old && index >= 0) update(sections.map(s => s.id === id ? old : s));
    else if (old) { const next = [...sections]; next.splice(Math.min(baseline.findIndex(s => s.id === id),next.length),0,old); update(next); }
    else update(sections.filter(s => s.id !== id));
  }
  const discussion = (data.comments ?? []).filter(c => c.documentId === source?.documentId && (!c.sectionId || c.sectionId === selected?.id));
  return <section className="agreement-editor card">
    <header className="editor-header"><div><span className="section-kicker">{data.contract.counterparty}</span><h3>Edit Agreement</h3></div><span className={`editor-save-state${dirty ? ' is-dirty' : ''}`} role="status">{busy === 'save' ? 'Saving…' : dirty ? 'Unsaved changes' : data.contract.version}</span></header>
    {data.request && <details className="workflow-disclosure"><summary>Business instructions <span>Terms from this request</span></summary><TermSheet terms={data.request.terms} /></details>}
    {canRevise && <form className="req-form editor-notice" onSubmit={e => { e.preventDefault(); void run('revise',async () => { const next = await reviseAgreement(data.contract.id,{ reason, revision: data.revision }); onChange(next); install(await getAgreementEditor(data.contract.id)); setReason(''); }); }}><p>This version is frozen. A revision preserves the previous decisions and requires fresh review and approval. An active signing package must be cancelled before it can be replaced.</p><label className="req-field">Reason for revision<textarea required maxLength={2000} rows={2} value={reason} onChange={e => setReason(e.target.value)} /></label><button className="btn btn-gold" disabled={!!busy}>Start controlled revision</button></form>}
    {source?.notice && <p className="editor-notice">{source.notice}</p>}{source?.trackedChanges && <label className="editor-notice req-check"><input type="checkbox" checked={reviewedTracked} onChange={e => setReviewedTracked(e.target.checked)} />I have reviewed the original and proposed Word changes.</label>}
    {error && <div className="editor-feedback"><RequestError message={error} /><button className="btn" disabled={!!busy} onClick={() => void run('compare',async () => { const latest = await getAgreementWorkspace(data.contract.id); const current = await getAgreementEditor(data.contract.id); if (dirty) { setConflict({ data: latest, source: current }); setCheckedConflict(false); } else { onChange(latest); install(current); } })}>{dirty ? 'Compare with current version' : 'Reload document'}</button></div>}
    {notice && <p className="editor-notice" role="status">{notice}</p>}
    {conflict && <section className="editor-conflict"><h3>A newer version is available</h3><p>Your unsaved language is preserved below. Review the differences before choosing which version to continue editing.</p><DocumentComparison before={identify(conflict.source.sections)} after={sections} /><label className="req-check"><input type="checkbox" checked={checkedConflict} onChange={e => setCheckedConflict(e.target.checked)} />I reviewed the current version and resolved the differences.</label><div className="req-actions"><button className="btn" onClick={() => { onChange(conflict.data); install(conflict.source); setConflict(undefined); }}>Use current saved version</button><button className="btn btn-gold" disabled={!checkedConflict} onClick={() => { onChange(conflict.data); setSource(conflict.source); setConflict(undefined); setReason('Reconciled edits against the latest saved version'); }}>Continue with my reconciled edits</button></div></section>}
    {!source && !error && <RequestLoading />}
    {source && !sections.length && !locked && <div className="editor-empty"><h3>Start the agreement here.</h3><p className="req-help">The counterparty and request stay connected to this draft.</p><label className="req-field">Approved template<select value={templateId} onChange={e => setTemplateId(e.target.value)}><option value="">Choose a template</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></label><button className="btn btn-gold" disabled={!!busy || !templateId} onClick={() => void run('template',async () => { const next = await startAgreementDraft(data.contract.id,{ templateId, revision: source.revision }); onChange(next); install(await getAgreementEditor(data.contract.id)); })}>Create from approved template</button><button className="btn" onClick={() => update([{ id: crypto.randomUUID(), heading: 'Parties', body: '' }])}>Start with a blank clause</button></div>}
    {!!sections.length && <>
      <div className="editor-toolbar" aria-label="Document tools"><button className="btn" disabled={locked || !!busy || !history.current.past.length} onClick={() => undo()}>Undo</button><button className="btn" disabled={locked || !!busy || !history.current.future.length} onClick={() => undo(true)}>Redo</button><button className="btn" aria-pressed={compare} onClick={() => setCompare(!compare)}>Compare changes</button>{source?.documentId && <a className="btn" href={`/api/documents/${source.documentId}/file`}>Download source</a>}<span className="req-help">{sections.length} clauses</span></div>
      {compare && <div className="editor-feedback"><DocumentComparison before={identify(source?.original ?? [])} after={sections} onRestore={locked ? undefined : restore} /></div>}
      <div className="editor-layout"><nav className="editor-outline" aria-label="Document clauses">{sections.map((s,i) => <button key={s.id} aria-current={i === active ? 'true' : undefined} onClick={() => { setActive(i); setProposal(undefined); }}><span>{String(i + 1).padStart(2,'0')}</span>{s.heading || 'Untitled clause'}</button>)}{!locked && <button disabled={!!busy || source?.preserveFormatting || sections.length >= 100} onClick={() => { update([...sections,{ id: crypto.randomUUID(), heading: `Clause ${sections.length + 1}`, body: '' }]); setActive(sections.length); }}>＋ Add clause</button>}</nav>
      <div className="editor-paper">{selected && <>
        <div className="editor-clause-controls"><span className="section-kicker">Clause {active + 1}</span>{!locked && <div><button className="btn" disabled={!!busy || source?.preserveFormatting || active === 0} onClick={() => { const next = [...sections]; [next[active-1],next[active]] = [next[active],next[active-1]]; update(next); setActive(active-1); }}>Move up</button><button className="btn" disabled={!!busy || source?.preserveFormatting || active === sections.length - 1} onClick={() => { const next = [...sections]; [next[active+1],next[active]] = [next[active],next[active+1]]; update(next); setActive(active+1); }}>Move down</button><button className="btn" disabled={!!busy || source?.preserveFormatting || sections.length === 1} onClick={() => { update(sections.filter((_,i) => i !== active)); setActive(Math.max(0,active-1)); }}>Delete</button></div>}</div>
        <label className="req-field editor-heading"><span className="sr-only">Clause heading</span><input maxLength={500} value={selected.heading} readOnly={locked || !!busy || selected.kind === 'paragraph'} onChange={e => edit({ heading: e.target.value })} /></label>
        <label className="req-field editor-language"><span className="sr-only">Clause language</span><textarea rows={14} maxLength={50000} value={selected.body} readOnly={locked || !!busy || source?.lockedSections?.includes(selected.id!)} onChange={e => edit({ body: e.target.value })} /></label>
        {!locked && <details className="workflow-disclosure"><summary>Drafting assistance <span>Approved clauses and AI proposals</span></summary><div className="req-form"><label className="req-field">Approved clause library<select value={clauseId} onChange={e => setClauseId(e.target.value)}><option value="">Choose a clause to insert</option>{clauses.map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button className="btn" disabled={!!busy || source?.preserveFormatting || !clauseId || sections.length >= 100} onClick={() => { const clause = clauses.find(c => c.id === clauseId)!; const next = [...sections]; next.splice(active+1,0,{ id: crypto.randomUUID(), heading: clause.title, body: clause.text }); update(next); setActive(active+1); }}>Insert after this clause</button><label className="req-field">Ask AI to revise this clause<textarea rows={2} maxLength={2000} value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="For example: make this mutual while preserving the liability cap" /></label><button className="btn" disabled={!!busy || !instruction.trim() || !selected.body.trim()} onClick={() => void run('ai',async () => { const p = await rewriteAgreementSection(data.contract.id,{ revision: source!.revision, heading: selected.heading, body: selected.body, instruction }); setProposal({ ...p, id: selected.id!, before: selected.body }); })}>{busy === 'ai' ? 'Preparing proposal…' : 'Suggest alternative language'}</button></div>{proposal && <section className="editor-proposal"><span className="badge neutral">AI proposal · review required</span><p>{proposal.body}</p><div className="req-actions"><button className="btn btn-gold" disabled={!!busy || selected.id !== proposal.id || selected.body !== proposal.before} onClick={() => { edit({ body: proposal.body }); setReason('AI-assisted clause revision reviewed by Legal'); setProposal(undefined); }}>Apply to draft</button><button className="btn" onClick={() => setProposal(undefined)}>Dismiss</button></div></section>}</details>}
        <details className="workflow-disclosure"><summary>Internal comments <span>{discussion.filter(c => !c.resolvedAt).length} open · visible only inside Legal</span></summary><ul className="editor-comments">{discussion.map(c => <li key={c.id}><b>{c.authorName}</b><small>{c.resolvedAt ? 'Resolved' : 'Open'}</small><p>{c.body}</p><button className="btn" disabled={!!busy} onClick={() => void run('comment',async () => onChange(await resolveAgreementComment(data.contract.id,c.id,!c.resolvedAt)))}>{c.resolvedAt ? 'Reopen' : 'Resolve'}</button></li>)}</ul><form className="req-form" onSubmit={e => { e.preventDefault(); void run('comment',async () => { onChange(await addAgreementComment(data.contract.id,{ id: crypto.randomUUID(), documentId: source!.documentId!, sectionId: selected.id, body: comment })); setComment(''); }); }}><label className="req-field">Comment on this saved clause<textarea rows={2} required maxLength={6000} value={comment} onChange={e => setComment(e.target.value)} /></label><button className="btn" disabled={!!busy || dirty || !source?.documentId || !comment.trim()}>Add internal comment</button>{dirty && <p className="req-help">Save this version before attaching a comment to it.</p>}</form></details>
      </>}</div></div>
    </>}
    {!locked && <div className="editor-footer"><label className="req-field">Version note<input maxLength={2000} value={reason} onChange={e => setReason(e.target.value)} placeholder="What changed in this revision?" /></label><div className="req-actions"><button className="btn btn-gold" disabled={!!busy || !source || !sections.length || (!dirty && !source.notice) || !!conflict || (source?.trackedChanges && !reviewedTracked)} onClick={() => void run('save',() => save())}>{busy === 'save' ? 'Saving version…' : 'Save new version'}</button>{source?.preserveFormatting && <button className="btn" disabled={!!busy || dirty || !!conflict || (source.trackedChanges && !reviewedTracked)} onClick={() => void run('external',() => save(true))}>Prepare clean external copy</button>}{data.contract.stage === 'drafting' && <button className="btn" disabled={!!busy || dirty || !source?.documentId || data.needsNewVersion} onClick={() => void run('review',async () => onChange(await changeAgreementStage(data.contract.id,{ stage: 'review', revision: source!.revision })))}>Continue to internal review →</button>}</div></div>}
    {!locked && <details className="workflow-disclosure editor-upload"><summary>Upload a revised document <span>Originals stay in Versions</span></summary><label className="req-field">Word, PDF or text<input type="file" accept=".pdf,.docx,.txt" disabled={!!busy || dirty} onChange={e => { const file = e.target.files?.[0]; if (!file) return; void run('upload',async () => { const results = await uploadFiles([file],data.contract.id); if (results.some(r => r.status === 'quarantined')) throw new Error('This document was quarantined. Review the file before uploading again.'); onChange(await getAgreementWorkspace(data.contract.id)); await load(); }); e.target.value = ''; }} /></label></details>}
  </section>;
}
