'use client';
import { useCallback, useEffect, useState } from 'react';
import { ApprovalWorkspaceData, getAgreementApprovals, routeAgreementApprovals, decideAgreementApproval } from '@/app/lib/api';
import { errorMessage, RequestError, RequestLoading } from './RequestUI';
export default function AgreementApprovals({ id, canRoute, onChange }: { id: string; canRoute: boolean; onChange: () => void }) {
  const [data,setData] = useState<ApprovalWorkspaceData>(); const [selected,setSelected] = useState<string[]>([]); const [note,setNote] = useState(''); const [comment,setComment] = useState(''); const [error,setError] = useState(''); const [busy,setBusy] = useState(false);
  const load = useCallback(async () => { setError(''); try { setData(await getAgreementApprovals(id)); } catch(e) { setError(errorMessage(e)); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function act(decision?: 'approved' | 'rejected' | 'changes-requested') { if (busy) return; setBusy(true); setError(''); try { setData(decision ? await decideAgreementApproval(id,{ decision, comment }) : await routeAgreementApprovals(id,{ approvers: selected, note })); onChange(); window.dispatchEvent(new Event('concord:inbox')); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  const required = data?.requirements?.flatMap(p => p.approvers) ?? [];
  return <section className="card card-pad agreement-approvals"><div className="agreement-section-head"><h3>Approval</h3>{data?.decision && <span className={`badge ${data.decision === 'approved' ? 'low' : 'med'}`}>{data.decision.replace('-',' ')}</span>}</div>{error && <RequestError message={error} retry={!data ? load : undefined} />}{!data ? !error && <RequestLoading /> : <>
  {!!data.steps.length && <><p className="req-help">Every required approver receives the same document version. Signature becomes available once all approvals are recorded.</p>{data.documentId && <a className="btn" href={`/api/documents/${data.documentId}/file`}>Open document for approval</a>}{data.recommendation && <div className="req-note"><b>Legal recommendation</b><p>{data.recommendation}</p></div>}<ol className="approval-timeline">{data.steps.map(s => <li key={s.id} data-status={s.decision}><span className="approval-step-mark" aria-hidden="true">{s.decision === 'approved' ? '✓' : s.decision === 'pending' ? '·' : '!'}</span><div><b>{s.approverName}</b><small>{s.approverEmail}</small><p>{s.reason}</p>{s.comment && <blockquote>{s.comment}</blockquote>}</div><span className="badge neutral">{s.decision.replace('-',' ')}</span></li>)}</ol></>}
  {data.canDecide && <form className="req-form" onSubmit={e => { e.preventDefault(); void act('approved'); }}><label className="req-field">Your decision note<textarea maxLength={2000} value={comment} onChange={e => setComment(e.target.value)} placeholder="Explain any conditions, rejection or changes required." /></label><div className="req-actions"><button className="btn btn-gold" disabled={busy}>Approve</button><button className="btn" type="button" disabled={busy || !comment.trim()} onClick={() => void act('changes-requested')}>Request Changes</button><button className="btn" type="button" disabled={busy || !comment.trim()} onClick={() => void act('rejected')}>Reject</button></div></form>}
  {!data.steps.length && !data.documentId && (canRoute ? <form className="req-form" onSubmit={e => { e.preventDefault(); void act(); }}><p className="req-help">Choose the authorised people required for this agreement. Your routing note should explain the exposure, deviations and Legal’s recommendation.</p>{!!data.requirements?.length && <div className="req-note"><b>Required by your approval policies</b>{data.requirements.map(p => <p key={p.policyId}>{p.reason}</p>)}</div>}<fieldset className="approver-options"><legend>Required approvers</legend>{data.available.map(p => <label key={p.id}><input type="checkbox" disabled={required.includes(p.email)} checked={required.includes(p.email) || selected.includes(p.email)} onChange={e => setSelected(v => e.target.checked ? [...v,p.email] : v.filter(x => x !== p.email))} /><span><b>{p.name}</b><small>{p.email}</small></span></label>)}{!data.available.length && <p>No other authorised approvers are available. An administrator needs to add an approver in Team &amp; access.</p>}</fieldset><label className="req-field">Legal recommendation &amp; material deviations<textarea required maxLength={4000} rows={4} value={note} onChange={e => setNote(e.target.value)} /></label><button className="btn btn-gold" disabled={busy || (!selected.length && !required.length)}>{busy ? 'Creating approval cards…' : 'Request approvals'}</button><p className="req-help">{data.outlookConfigured ? 'Approvers are notified in Concord and Outlook.' : 'Approval cards work in Concord. Outlook email is awaiting Microsoft configuration.'}</p></form> : <p className="req-help">The legal owner will request the required approvals when the agreement is ready.</p>)}
  {!data.steps.length && data.documentId && <p className="req-help">This agreement was routed through the existing Outlook approval flow. Its decision and document remain preserved.</p>}
  </>}</section>;
}
