'use client';
import { useRef, useState } from 'react';
import type { ClientRequest } from '@concord/shared';
import { postRequestMessage } from '@/app/lib/api';
import { errorMessage, requestDate, RequestError } from './RequestUI';
export default function RequestConversation({ item, onChange }: { item: ClientRequest; onChange: (item: ClientRequest) => void }) {
  const [body,setBody] = useState(''); const [kind,setKind] = useState<'question' | 'reply' | 'update'>(item.canManage ? 'question' : 'reply'); const [busy,setBusy] = useState(false); const [error,setError] = useState(''); const [saved,setSaved] = useState(''); const key = useRef('');
  return <section className="card card-pad request-conversation"><div className="agreement-section-head"><h3>{item.canManage ? 'Business input' : 'Conversation with Legal'}</h3><span className="req-id">{item.messages?.length ?? 0} messages</span></div>{item.legalNote && !item.messages?.some(m => m.body === item.legalNote) && <p className="req-note">{item.legalNote}</p>}<ol className="conversation-list">{item.messages?.map(m => <li key={m.id} data-kind={m.kind}><div><b>{m.authorName}</b><small>{requestDate(m.createdAt)} · {m.kind === 'question' ? 'Action required' : m.kind === 'reply' ? 'Business input' : 'Update'}</small></div><p>{m.body}</p></li>)}</ol>{!item.messages?.length && <p className="req-help">Questions and answers stay with this agreement, so everyone keeps the same context.</p>}{item.status !== 'closed' && <form className="req-form" onSubmit={async e => { e.preventDefault(); if (busy) return; setBusy(true); setError(''); setSaved(''); if (!key.current) key.current = crypto.randomUUID(); try { const next = await postRequestMessage(item.id, { id: key.current, body, kind, version: item.version }); onChange(next); setBody(''); key.current = ''; setSaved('Message saved. The recipient has been notified in Concord.'); window.dispatchEvent(new Event('concord:inbox')); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }}>
  {item.canManage && <label className="req-field">Message type<select value={kind} disabled={busy} onChange={e => { setKind(e.target.value as 'question' | 'update'); key.current = ''; }}><option value="question">Request business input</option><option value="update">Share a progress update</option></select></label>}<label className="req-field">{item.canManage ? kind === 'question' ? 'What do you need confirmed?' : 'Update for the requestor' : 'Your response'}<textarea required maxLength={4000} rows={3} value={body} disabled={busy} onChange={e => { setBody(e.target.value); key.current = ''; }} placeholder={item.canManage ? 'e.g. Please confirm the proposed liability cap.' : 'Share the information Legal needs.'} /></label>{error && <RequestError message={error} />}{saved && <p role="status" className="req-success">{saved}</p>}<div className="req-actions"><button className="btn btn-gold" disabled={busy || !body.trim()}>{busy ? 'Sending…' : item.canManage && kind === 'question' ? 'Request business input' : 'Send message'}</button></div></form>}</section>;
}
