'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import type { ClientRequest } from '@concord/shared';
import { getClientRequest } from '@/app/lib/api';
import { errorMessage, requestDate, RequestError, RequestHeader, RequestLoading, RequestStatus, TermSheet } from '@/components/RequestUI';
import LifecycleRail from '@/components/LifecycleRail';
import RequestConversation from '@/components/RequestConversation';
export default function RequestDetail({ params }: { params: { id: string } }) {
  const [item,setItem] = useState<ClientRequest>(); const [error,setError] = useState(''); const [submitted,setSubmitted] = useState(false);
  const load = useCallback(async () => { setError(''); try { setItem(await getClientRequest(params.id)); } catch(e) { setError(errorMessage(e)); } }, [params.id]);
  useEffect(() => { void load(); setSubmitted(new URLSearchParams(window.location.search).get('submitted') === '1'); }, [load]);
  return <div className="req-page"><Link className="req-back" href="/requests">← My Requests</Link>{error ? <RequestError message={error} retry={load} /> : !item ? <RequestLoading /> : <>
  {submitted && <section className="request-confirmation" role="status"><span className="confirmation-mark" aria-hidden="true">✓</span><span className="eyebrow">You’re all set</span><h2>Request {item.id} submitted</h2><p><b>{item.assignedLegal.name}</b> is your legal contact. The next step is Legal’s review of your term sheet.</p><button className="btn" onClick={() => setSubmitted(false)}>Follow your request below ↓</button></section>}
  <RequestHeader kicker={`${item.id} · ${item.contractType}`} title={item.title} description={`${item.counterparty} · ${item.businessUnit}`} action={<RequestStatus status={item.status} />} />
  <LifecycleRail requestor stage={item.contractStage} waiting={item.status === 'waiting-on-client'} executed={item.contractStage === 'active'} />
  <section className="agreement-focus card card-pad"><div><span className="section-kicker">{item.status === 'waiting-on-client' ? 'Action required' : 'Next step'}</span><h3>{item.status === 'waiting-on-client' ? 'Legal needs your input' : item.status === 'closed' ? item.contractStage === 'active' ? 'Agreement completed' : 'Request closed' : item.contractStage === 'intake' ? 'Legal will review your request' : 'Your legal team is progressing the agreement'}</h3><p>{item.status === 'waiting-on-client' ? 'Read the question below and send your response.' : `Your contact: ${item.assignedLegal.name}`}</p></div><div><small>Requested by</small><b>{requestDate(item.requestedByDate)}</b></div></section>
  <div className="req-detail-grid"><div className="agreement-main"><RequestConversation item={item} onChange={setItem} /><details className="card card-pad workflow-disclosure"><summary>Submitted term sheet<span>Saved {requestDate(item.createdAt)}</span></summary><TermSheet terms={item.terms} /></details>{!!item.attachments?.length && <section className="card card-pad"><h3>Documents</h3><ul className="attachment-list">{item.attachments.map(a => <li key={a.id}><span><b>{a.filename}</b><small>{a.category}</small></span><a className="btn" href={`/api/request-attachments/${a.id}/file`}>Download</a></li>)}</ul></section>}</div><aside className="req-aside"><section className="req-panel"><span className="eyebrow">Your legal contact</span><div className="req-person"><span className="req-avatar" aria-hidden="true">{item.assignedLegal.name.split(/\s+/).map(p => p[0]).slice(0,2).join('')}</span><div><b>{item.assignedLegal.name}</b><a href={`mailto:${item.assignedLegal.email}`}>{item.assignedLegal.email}</a></div></div><p className="req-help">{item.assignmentPreference}</p><dl className="req-meta"><div><dt>Requestor</dt><dd>{item.requester.name}</dd></div><div><dt>Priority</dt><dd>{item.urgency}</dd></div></dl>{item.canOpenAgreement && <Link className="btn btn-gold" href={`/contracts/${encodeURIComponent(item.contractId)}`}>Open agreement workspace →</Link>}</section></aside></div>
  </>}</div>;
}
