'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ApproverCard, getApproverCard, decideAgreementApproval } from '@/app/lib/api';
import { errorMessage, RequestError, RequestLoading } from '@/components/RequestUI';
export default function ApprovalCardPage({ params }: { params: { id: string } }) {
  const [data,setData] = useState<ApproverCard>(), [error,setError] = useState(''), [comment,setComment] = useState(''), [reviewed,setReviewed] = useState(false), [busy,setBusy] = useState(false);
  const load = useCallback(async () => { setError(''); try { setData(await getApproverCard(params.id)); } catch(e) { setError(errorMessage(e)); } },[params.id]);
  useEffect(() => { void load(); },[load]);
  async function decide(decision: 'approved' | 'rejected' | 'changes-requested') { if (busy) return; setBusy(true); setError(''); try { await decideAgreementApproval(params.id,{ decision, comment }); await load(); window.dispatchEvent(new Event('concord:inbox')); } catch(e) { setError(errorMessage(e)); } finally { setBusy(false); } }
  if (!data) return error ? <RequestError message={error} retry={load} /> : <RequestLoading />;
  const c = data.contract, a = data.approval;
  return <div className="approver-detail"><Link className="req-back" href="/approvals">← My Approvals</Link><header className="agreement-header"><div><span className="eyebrow">Approval · {a.contractVersion}</span><h2>{c.title}</h2><p>{c.counterparty}</p></div><span className="badge neutral">{a.decision?.replace('-',' ') || 'Approval pending'}</span></header><section className="card card-pad"><h3>What you’re being asked to approve</h3><p className="agreement-scope">{data.assignedReason}</p><dl className="agreement-facts"><div><dt>Agreement</dt><dd>{c.type}</dd></div><div><dt>Financial exposure</dt><dd>{c.valueDisplay}</dd></div><div><dt>Recorded risk</dt><dd>{c.risk}</dd></div><div><dt>Document version</dt><dd>{a.contractVersion}</dd></div></dl><div className="editor-notice"><b>Legal recommendation &amp; material deviations</b><p>{a.recommendation || 'No additional recommendation recorded. Ask Legal if you need further context.'}</p></div>{data.expired ? <p className="req-note">This approval card has expired. Ask Legal for an updated request.</p> : <a className="btn btn-gold" href={`/api/approvals/${encodeURIComponent(c.id)}/file`}>Open the exact document for approval</a>}<details className="workflow-disclosure"><summary>Document integrity</summary><p className="integrity-hash">SHA-256: {a.documentSha256}</p></details></section>
  <section className="card card-pad"><h3>Approval progress</h3><ol className="approval-timeline">{a.steps.map(s => <li key={s.id} data-status={s.decision}><span className="approval-step-mark" aria-hidden="true">{s.decision === 'approved' ? '✓' : '·'}</span><div><b>{s.approverName}</b><p>{s.reason}</p>{s.comment && <blockquote>{s.comment}</blockquote>}</div><span className="badge neutral">{s.decision.replace('-',' ')}</span></li>)}</ol>{error && <RequestError message={error} />}{a.canDecide && !data.expired && <form className="req-form" onSubmit={e => { e.preventDefault(); void decide('approved'); }}><label className="req-field">Your decision note<textarea maxLength={2000} rows={3} value={comment} onChange={e => setComment(e.target.value)} placeholder="Record conditions, questions or changes required." /></label><label className="req-check"><input type="checkbox" checked={reviewed} onChange={e => setReviewed(e.target.checked)} />I have reviewed the document and the request above.</label><div className="req-actions"><button className="btn btn-gold" disabled={busy || !reviewed}>Approve</button><button className="btn" type="button" disabled={busy || !comment.trim()} onClick={() => void decide('changes-requested')}>Request Changes</button><button className="btn" type="button" disabled={busy || !comment.trim()} onClick={() => void decide('rejected')}>Reject</button></div></form>}</section></div>;
}
